### PR TITLE
Adding MageCoin (MAG) ERC20 Token metadata

### PR DESCRIPTION
**Pull request by magecoin**

### CODE REVIEW

**Comment by magecoin** [comment]
@danfinlay who can review this PR?

**Comment by danfinlay** [comment]
I can, but I don't like excessive pings. These merges can be slow, please be patient, we do diligence.

**Comment by magecoin** [comment]
@DaveAppleton @mintheredonethat @crowdstartcapital @thehighfiveghost @canya-io @markshw @abhisingla280 @brynbellomy @lastperson @kumavis @webjunkie01 @daytonmills @abcoathup @simondlr @lukezhangstudio @neptox @brainfrog @MicahZoltu @miohtama @sebastian-stephan @protinam is this PR okay? Not sure who I request to approve it... Thanks in advance!

**Comment by magecoin** [comment]
@danfinlay got it, thanks for the quick response!

Thanks again,
Sam

**Comment by danfinlay** [comment]
Oh wow, are you kidding? You seriously pinged all those people at once, then deleted the comment? That's damn rude.

**Comment by protinam** [comment]
Why was I pinged - I have nothing to do with this repository, and I have no idea what "Magecoin" is.

Any way to turn this feature off?

**Comment by daytonmills** [comment]
Wooo parttyy!!!

**Comment by danfinlay** [comment]
The guy pinged a ton of people for no reason. As far as I can tell, this coin is a scam, I can't endorse it, rejecting the PR.

**Pull request closed without merging**
