### PR TITLE
[ADD]BC & BEFC Token

### PR DESCRIPTION
**Pull request by bgjio**
Etherscan: https://etherscan.io/token/0x5c38fc75474d1bef3d66f81bfb89c4bf6e65f0a4
Project website: https://www.bgj.io/
Twitter: https://twitter.com/bgj_io
Telegram: https://t.me/joinchatHHbi4xDqMT
Github: https://github.com/bgjio
Reddit: https://www.reddit.com/user/bgj_io

### CODE REVIEW

**Comment by bgjio** [comment]
fixed the befc contract address issue.

**Comment by bgjio** [comment]
please add both bc and befc token, thanks.

**Comment by bgjio** [comment]
Hi @estebanmino, thanks for your reply.
Could u tell me how to make befc or bc be NEUTRAL reputation? I've updated the official link or the other info on etherscan.io, but I cant find the info or property about the "NEUTRAL reputation".

**Comment by estebanmino** [comment]
Hey @bgjio this is it https://etherscancom.freshdesk.com/support/solutions/articles/35000022146-etherscan-token-reputation-system

**Comment by estebanmino** [comment]
@bgjio closing this due to inactivity, feel free to reopen.

**Pull request closed without merging**
