### PR TITLE
Update stormx.svg

### PR DESCRIPTION
**Pull request by alexhidalgo**
Recent branding change for the logo
https://coinmarketcap.com/currencies/stormx/
https://www.coingecko.com/en/coins/stormx
https://stormx.io/token

### CODE REVIEW

**Comment by xrn** [comment]
Hi, @alexhidalgo thanks for the update. I have a question about our contract-map should we still keep STORM token with an image or after your successfully swap to STMX it deprecated?

**Comment by alexhidalgo** [comment]
> Hi, @alexhidalgo thanks for the update. I have a question about our contract-map should we still keep STORM token with an image or after your successfully swap to STMX it deprecated?

Lets remove STORM. Its deprecated. Thanks for checking!

**Review by xrn — APPROVED** [review]

**Comment by xrn** [comment]
@alexhidalgo may I ask you to prepare a pull request which will remove Storm from JSON and SVG. I will approve it then and merge - thanks

**Comment by alexhidalgo** [comment]
> @alexhidalgo may I ask you to prepare a pull request which will remove Storm from JSON and SVG. I will approve it then and merge - thanks

Yes will do!

**Comment by xrn** [comment]
@alexhidalgo any progress here :) ?

**Comment by alexhidalgo** [comment]
@xrn i just created a PR to remove old info and logo here https://github.com/MetaMask/eth-contract-metadata/pull/599

**Pull request merged**
