### PR TITLE
Gitcoin add

### PR DESCRIPTION
**Pull request by NukeManDan**

### CODE REVIEW

**Comment by NukeManDan** [comment]
[Gitcoin](https://gitcoin.co) uses ETH/ERC20 tips and bounties to incentivize work in Open Source Software; with the stated mission to "Grow Open Source"

**Comment by NukeManDan** [comment]
@danfinlay - Any chance we can get approved? :smiley:

**Comment by kumavis** [comment]
@NukeManDan im confused, gitcoin is not a token

> 1. It's *not* a token. There is *no* native token on the Gitcoin community. We're focused on honing our product/market fit.

**Comment by owocki** [comment]
chatted with @kumavis and @markbeylin about this... after thinking about it.. we think that the contract name should be 'StandardBounties' and the logo should be the bounty bee ( https://bounties.network/images/logo.svg ) instead of the gitcoin logo

**Comment by mbeylin** [comment]
The name should be "StandardBounties" and the attached image should be used
bee_square_large

**Comment by NukeManDan** [comment]
That work for everyone?

**Comment by owocki** [comment]
LGTM

**Comment by mbeylin** [comment]
Looks good to me.

**Pull request merged**
