### PR TITLE
Adds ETHLend Token

### PR DESCRIPTION
**Pull request by sirsoth**
ETHLend token addition in contract-map.json and lend.svg added to images folder

Source on etherscan:
https://etherscan.io/token/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03

Project website:
https://ethlend.io

Dapp website:
https://app.ethlend.io/

Project whitepaper:
https://github.com/ETHLend/Documentation/blob/master/ETHLendWhitePaper.md

Public logo:
https://github.com/ETHLend/logos

### CODE REVIEW

**Comment by sirsoth** [comment]
All problems solved, metamask reputation neutral, all necessary data published, if you need anything else more just let me know.

**Comment by sirsoth** [comment]
Hello @estebanmino, Thanks for your review, I have deleted the old logo and added a new one in svg format with a size less than 2KB.

**Comment by estebanmino** [comment]
@sirsoth  perfect, thanks.

**Comment by sirsoth** [comment]
@estebanmino Thanks a lot, when would be our token updated in metamask? In the next update?

**Comment by estebanmino** [comment]
@sirsoth yes, in the next release.

**Pull request merged**
