### PR TITLE
adding BitClave's CAT token

### PR DESCRIPTION
**Pull request by markshw**
website: https://www.bitclave.com

### CODE REVIEW

**Comment by danfinlay** [comment]
Can you link to a page where their website references the contract address you've provided?

**Comment by markshw** [comment]
@danfinlay , I changed token address and name to 0x1234567461d3f8db7496581774bd869c83d51c93 CAT and here is the link to official BitClave page: https://medium.com/@BitClave/adding-cat-tokens-to-your-wallet-a1771fbe513d

**Comment by markshw** [comment]
Hi @danfinlay , I do not see the logo for BitClave showing up. Is there any problem with the bitclave.svg file?

**Comment by danfinlay** [comment]
This is not an instant process. Please wait for the next MetaMask release.

**Comment by markshw** [comment]
But the token is already showing up. Are you saying the logo is different process? I’m wondering if there is some issue with the logo file
Thanks a lot for your prompt response

**Comment by markshw** [comment]
Actually, I’m not 100% sure if it is showing up automatically - it might be that I added it manually.
Can you please check if 0x1234567461d3f8db7496581774bd869c83d51c93 is already completely integrated and is supposed to load automatically?

**Comment by danfinlay** [comment]
We do not currently show any tokens automatically.

**Comment by markshw** [comment]
I see…
Can you please check if 0x1234567461d3f8db7496581774bd869c83d51c93 is already completely integrated and the logo is expected to show up

**Comment by danfinlay** [comment]
Yes, it is merged.

**Pull request merged**
