### PR TITLE
Added Tulip Token

### PR DESCRIPTION
**Pull request by thetulipauction**

### CODE REVIEW

**Comment by flyswatter** [comment]
Thanks for the PR, we're willing to re-consider this once this token has more than one in circulation.

**Comment by thetulipauction** [comment]
@flyswatter Thanks for taking a look at the PR. I'm not sure if you're familiar with the project or had a chance to skim the [whitepaper](https://thetulip.auction/static/The_Tulip_Whitepaper.pdf), but the whole design of the token is that there is only 1 of it in circulation and it will go to the highest bidder of the auction.

**Comment by flyswatter** [comment]
Okay, we'll reconsider when it has more activity, I'll try to check it out later!

**Comment by thetulipauction** [comment]
Great, will ping when the auction goes live, thanks!

**Pull request closed without merging**
