### PR TITLE
Added metadata for token contracts based off etherscan.io/tokens

### PR DESCRIPTION
**Pull request by mintheredonethat**
- Non-svg images are < 300x300 (9 PNG & 1 JPG)
- Couldn't find image for vSlice
- Many svg images are large

Looking forward to your feedback & how I can improve my submission process 😃

### CODE REVIEW

**Comment by flyswatter** [comment]
I've added you as a contributor to the repo so that you can push your branches to the main remote (which is required for the test suite to trigger).

The test suite caught a JSON error (yay test suite!)

Thanks for adding extra data for tokens. Like I'd said in #1, this is really useful for rendering tokens that don't follow the human-readable standard (providing methods for getting name/symbol/precision).

That said, we're probably including more metadata here than we need to. Especially if this database grows very large, we're going to want to try to keep it as lean as possible.

I'm also happy to help prune fields that we agree aren't "universally useful", but here let's discuss what fields we might actually find useful to include.

The obvious fields that we already include for ENS are:
- logo
- name

I think some additional fields are easily merited for tokens. To help readers know whether an item *is* a token, I was thinking we could have a field like `erc20: true`.

Other fields that are special for human-readable tokens but aren't universal to tokens (making them useful off-chain data) are:

- name (duplicate)
- symbol
- decimals

Beyond that, I see a lot of fields here that are either specific or unique to that contract, or are really contract methods for all tokens, and so they shouldn't need to be stored in a permanent-ish file like this.  Running a quick script I found 116 unique keys here, and most of them are only used once. I think that's too many to be useful for standard consumption, so I think we should maybe enforce a strict set of permitted keys, and add it to the test suite.

How does that sound?

**Comment by flyswatter** [comment]
I've added a fix and some new tests on [this branch](https://github.com/MetaMask/eth-contract-metadata/tree/bug/add-special-fields-for-tokens-%232).

Thank you so much for submitting this btw!  I just want to make sure we have it tight and clean, but this is going to be a huge boost for MetaMask's UX!

**Comment by mintheredonethat** [comment]
Thank you for the awesome, clear, and actionable feedback. I am on the same page about keeping things lean and will clean things up with respect to the [permitted fields](https://github.com/MetaMask/eth-contract-metadata/blob/bug/add-special-fields-for-tokens-%232/permitted-fields.json). Should I push up the changes from this same branch (mintheredonethat:bug/add-special-fields-for-tokens-#2) & submit another PR to Metamask:master?

**Comment by mintheredonethat** [comment]
Pushed up to [main's bug/add-special-fields-for-tokens-#2 branch](https://github.com/MetaMask/eth-contract-metadata/tree/bug/add-special-fields-for-tokens-%232)

**Comment by flyswatter** [comment]
I think the only way we can get a branch where we both get tests running on it is if you open a new PR from the master branch, so I'll close this one and open that.

**Pull request closed without merging**
