### PR TITLE
Add EOS metadata & logo

### PR DESCRIPTION
**Pull request by mintheredonethat**
Not a square image

### CODE REVIEW

**Comment by flyswatter** [comment]
Think we could get a square image with a black background? This transparency basically requires a dark background.

**Comment by mintheredonethat** [comment]
eos-logo
How's this? Found a 700x700 & resized to 300x300. It's a jpeg though

**Comment by flyswatter** [comment]
Better to avoid text, and to crop the image close to the logo, since this will be rendered inside a small circle for MetaMask.

**Comment by mintheredonethat** [comment]
eos-logo-large
Cropped & resized.

**Comment by flyswatter** [comment]
That looks perfect, could you add it to the PR branch itself?

**Pull request merged**
