### PR TITLE
Add weth

### PR DESCRIPTION
**Pull request by BMillman19**
https://github.com/MetaMask/eth-contract-metadata/issues/73

https://weth.io/

https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

### CODE REVIEW

**Comment by estebanmino** [comment]
Please provide additional details per the latest submission guidelines, and re-submit when ready.

- [ ] Must have a 'NEUTRAL' reputation or 'OK' reputation on Etherscan.

**Comment by tomhschmidt** [comment]
@estebanmino Added on Etherscan https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

**Comment by BMillman19** [comment]
@estebanmino @danfinlay bump again

**Comment by rekmarks** [comment]
WETH added to master.

**Comment by rekmarks** [comment]
For posterity: closed because GitHub complained about merge conflicts after merge was attempted, even though master is complete up to date with this PR.

**Pull request closed without merging**
