### PR TITLE
Update VIDT contract address in response to KuCoin hack

### PR DESCRIPTION
**Pull request by Sjazzz**
Please update our contract address as we are preparing a token swap to all holders.
Correct addres is https://etherscan.io/address/0xfef4185594457050cc9c23980d301908fe057bb1.

For evidence ...
1) https://twitter.com/VIDT_Datalink/status/1311709500404006913
2) The new contract was deployed by the same account (0x95cc85867d633db0c0abd05f6cff7d45f7ece315)
3) The new smart contract address is mentioned here https://about.v-id.org/token/
4) The old contract has been paused and will not function anymore
5) New tokens will be reissued 1:1 and automatically distributed to the holders of the previous token (to be completed in 4 days)

### CODE REVIEW

**Review by melyalex — APPROVED** [review]

**Comment by Sjazzz** [comment]
Added the new BEP20 version of VIDT also ...

Thank you for your time!

**Comment by xrn** [comment]
Hi @Sjazzz this repository has limitation to not confuse users that in a map can be only 1 token with a given symbol - please update this PR thanks

**Comment by Sjazzz** [comment]
Thanks xrn, updated contract-map.json and added a distinguishing logo.

Thanks!

**Comment by xrn** [comment]
@Sjazzz thanks for the updates - as you see tests are failing because contract addresses have to follow EIP-55. Can you fix it, please?

**Comment by Sjazzz** [comment]
All checks passed now, cheers!

**Comment by xrn** [comment]
@Sjazzz - thanks I am reviewing it now and seems that there is no case to add the BEP version of the token to this repository. MetaMask is supporting only Ethereum powered tokens. Please remove it because in the Ethereum network this address do not have activity - https://etherscan.io/address/0x3f515f0a8e93F2E2f891ceeB3Db4e62e202d7110

**Comment by Sjazzz** [comment]
Removed the BEP20 version

**Comment by xrn** [comment]
* https://hotbit.zendesk.com/hc/en-us/articles/360057510593-Announcement-Regarding-Completing-VIDT-Contract-Address-Upgrade-and-Opening-of-Withdrawal-and-Deposit-Functions-of-VIDT-on-Hotbit
* https://github.com/V-ID/V-ID-Token

**Review by xrn — APPROVED** [review]

**Pull request merged**
