### PR TITLE
ajout BTU contract

### PR DESCRIPTION
**Pull request by pelluro**
Add BTU crypto currency.

### CODE REVIEW

**Comment by pelluro** [comment]
Website: [https://www.btu-protocol.com/en/](https://www.btu-protocol.com/en/)
Github: [https://github.com/btuprotocol](https://github.com/btuprotocol)
Etherscan: [https://etherscan.io/token/0xb683D83a532e2Cb7DFa5275eED3698436371cc9f](https://etherscan.io/token/0xb683D83a532e2Cb7DFa5275eED3698436371cc9f)

**Comment by pelluro** [comment]
Hi @estebanmino , you can learn more about us here and see that we are active :

1/  We are the Inventor of EIP 808 and BTU token is the first implementation => [https://github.com/ethereum/EIPs/pull/808](https://github.com/ethereum/EIPs/pull/808)

2/ We've raised about 5.5 millions dollars for the ICO  =>  [http://www.rudebaguette.com/2018/05/18/buy-tokens-in-a-store-btu-protocol/](http://www.rudebaguette.com/2018/05/18/buy-tokens-in-a-store-btu-protocol/)

3/ We're lauching our product in BtoC for the 8th of January that's why we want to be listed on metamask => [https://medium.com/@BTUProtocolTeam/btu-protocol-the-first-blockchain-booking-system-is-selected-to-exhibit-at-ces-2019-in-las-vegas-1afc2f1cc708](https://medium.com/@BTUProtocolTeam/btu-protocol-the-first-blockchain-booking-system-is-selected-to-exhibit-at-ces-2019-in-las-vegas-1afc2f1cc708)

Thanks for reviewing our request.
Regards,

**Comment by pelluro** [comment]
hi @estebanmino

anything I can do for this approval ?

Thank you :)

**Comment by pelluro** [comment]
hi @estebanmino,
Now we have much more activity and we really need BTU to be added. We are also listed on serious exchange Bittrex. Also there is risk other people are faking our token !
[https://international.bittrex.com/Market/Index?MarketName=BTC-BTU](https://international.bittrex.com/Market/Index?MarketName=BTC-BTU)

**Comment by estebanmino** [comment]
Hi @pelluro did you notice that you added Dether address in your changes? Please change it in order to merge. Thanks

**Comment by pelluro** [comment]
Hi @estebanmino , thank for your warning, the BTU contract has been updated ! Thank you so much.

**Comment by estebanmino** [comment]
Please fix conflicts. Thanks

**Comment by pelluro** [comment]
> Please fix conflicts. Thanks

Done ! I think you need to discard the "Changes requested" because it is still with the wrong address. I hope everything is ok for you now !

**Comment by pelluro** [comment]
@estebanmino Any update please ? Thank you !

**Pull request merged**
