### PR TITLE
Added EGO album badge.

### PR DESCRIPTION
**Pull request by simondlr**

### CODE REVIEW

**Comment by flyswatter** [comment]
Long term it's going to be worth looking at new ways for pulling up this database, b/c if there's an entry for every album, it's going to become big. But for now, I think it's a nice promotion for Ujo.

**Comment by simondlr** [comment]
Might be time to start looking into a token registry of sorts? Time to repeal that conversation again? ;)

Might also be useful to take a look at how etherscan detects ERC20's. It does automatically by watching for Transfer() events with those addresses. Not sure if they do deeper diligence than that. Perhaps they have an API for this?

**Comment by flyswatter** [comment]
The difference is that we're doing this logic on every client, while they're offering a backend analysis service. It's easy for a small farm of servers to watch every tx on the blockchain and detect tokens, it's another thing for every wallet to do the same, especially a light wallet like MetaMask, that doesn't even validate blocks yet. For a super thin client like this, it needs to be fed some extra data to get its leg up. That can either be the user clicking "add token" (crap UX) or a centralized registry (what this is, but could be more sophisticated).

I know the Balanc3 team is doing a lot of token analysis, so they might eventually provide the "tokens for address" api endpoint, Etherscan doesn't yet.

**Comment by flyswatter** [comment]
Sorry, I had "run tests on external PRs" turned off to prevent a mining attack, I need to PR this from the same remote, your commits will still be in.  Closing in favor of #21.

**Comment by simondlr** [comment]
Aye. Yeah. Makes sense. :) @flyswatter

**Pull request closed without merging**
