### PR TITLE
Adding VDOC 

### PR DESCRIPTION
**Pull request by cameronbedford**

### CODE REVIEW

**Comment by danfinlay** [comment]
Please provide additional details per the latest submission guidelines, and re-submit when ready.

- The icon should be small, square, but high resolution, ideally a vector/svg.
- Do not add your entry to the end of the JSON map, messing with the trailing comma. Your pull request should only be an addition of lines, and any line removals should be deliberate deprecations of those logos.
- PR should include link to official project website referencing the suggested address.
- Project website should include explanation of project.
- Project should have clear signs of activity, either traffic on the network, activity on GitHub, or community buzz.
- Nice to have a verified source code on a block explorer like Etherscan.

**Comment by cameronbedford** [comment]
Thanks @danfinlay for that.   Can you help me understand more of what may be missing that is preventing that being added?

- We've got the Icon, 
- not added to the end of the JSON map
- The link to the [official project website is here](https://dutyof.care/token-launch/#step-5) which includes reference to the purchasing instructions and will very shortly include reference to the Token itself.
- the [dutyof.care main website](https://dutyof.care) talks about the platform we're building and the [token launch](https://dutyof.care/token-launch/) about the process.
- we have traffic on the network and [tokens being purchased](https://etherscan.io/token/0x82bd526bdb718c6d4dd2291ed013a5186cae2dca).

Anything else you need?

Cheers

**Comment by danfinlay** [comment]
Yeah, waiting for the token address to be referenced on an official source. Please ping here again when it does.

**Comment by cameronbedford** [comment]
Thanks @danfinlay .   We now have the token address up on our [token-launch](https://dutyof.care/token-launch/#step-5) site.   In addition to the Etherscan address, I provided previously, is that sufficient?

**Comment by danfinlay** [comment]
Sorry, token logos must be square.

**Comment by cameronbedford** [comment]
superseded by #79

**Pull request closed without merging**
