### PR TITLE
Added Maecenas ART Token

### PR DESCRIPTION
**Pull request by reiven**
Added ART Token, cleanead up some empty lines

### CODE REVIEW

**Comment by flyswatter** [comment]
Tests failed, please provide the token address in the checksum format.

**Comment by reiven** [comment]
Sure, changed to checksum format

**Comment by kumavis** [comment]
@reiven  we need a verification that the supplied address is correct an evidence of token activity

**Comment by reiven** [comment]
Sure, this a screenshot of Etherscan.io

image

Also a screenshot of coinmarketcap.com

image

Let me know if you need anything else. 

Thanks

**Pull request merged**
