### PR TITLE
Add VDOC Token

### PR DESCRIPTION
**Pull request by cameronbedford**
Hi.

Superseeding PR #70  

- We've got the Icon (now square), 
- not added to the end of the JSON map
- The link to the [official project website is here](https://dutyof.care/token-launch/#step-5) which includes reference to the purchasing instructions and will very shortly include reference to the Token itself.
- the [dutyof.care main website](https://dutyof.care) talks about the platform we're building and the [token launch](https://dutyof.care/token-launch/) about the process.
- we have traffic on the network and [tokens being purchased](https://etherscan.io/token/0x82bd526bdb718c6d4dd2291ed013a5186cae2dca).

Anything else you need?

Cheers

### CODE REVIEW

**Comment by cameronbedford** [comment]
Hello - can I have an update on this PR please?

**Comment by cameronbedford** [comment]
@miohtama  @brynbellomy  @webjunkie01  @drdaeman  @danfinlay 
Hello - looking for some help to get some progress here please.   I was having a dialog with Dan and have resolved the issues on this new PR, however it's been nearly a month and it's stuck pending review.   Would it be possible to have one of you help this progress please.

Thanks in advance

**Comment by RickyCook** [comment]
hey @frankiebee, i'm a little confused here. our token has been neutral on etherscan for ~7 weeks?

screen shot 2018-04-17 at 13 35 03

**Comment by frankiebee** [comment]
ooh woops sorry about that @RickyCook

**Comment by frankiebee** [comment]
ooh woops sorry about that @RickyCook do you guys have a github?

**Comment by RickyCook** [comment]
organization github is here https://github.com/bluebikesolutions/

the product itself is still in closed beta, so we haven't released any OSS components just yet

**Comment by RickyCook** [comment]
... although, our ICO repo/branch is https://github.com/BlueBikeSolutions/ico/tree/doc-launch-2

**Comment by RickyCook** [comment]
thanks @frankiebee ! looking forward to having VDOC in my browser for real :P

**Pull request merged**
