### PR TITLE
add HERC Token Logo to Metamask! 

### PR DESCRIPTION
**Pull request by lrgeoemtry**
👋 im logan, cto of HERC and i'm just now able to make this pull request! 
i *think* i did it right but if i didn't let me know! 
thanks :) 
logan ryan golema 
cto 
https://herc.one

### CODE REVIEW

**Comment by lrgeoemtry** [comment]
Hi @estabanmino so weird we dont have neutral rep as we are fully transparent on etherscan and our website. Ill reach out to them and zee why theres a hold up. 

We've set up the https://add.herc.one dapp so its a good start :) 

Ill let you know when the rep is neutral.

**Comment by lrgeoemtry** [comment]
oic i need to checksum the contract addr

**Comment by lrgeoemtry** [comment]
@estebanmino tada!

**Comment by lrgeoemtry** [comment]
@estebanmino

**Comment by lrgeoemtry** [comment]
@estebanmino dude, passing all requirements can you merge this pl0x <3

**Comment by lrgeoemtry** [comment]
@estebanmino there was something to be resolved due to syntax, this has now been achieved.

**Comment by lrgeoemtry** [comment]
@estebanmino is this cool to merge today?

**Comment by estebanmino** [comment]
Hi @lrgeoemtry I recommend you to take a look to `watchAsset` documentation [here](https://metamask.github.io/metamask-docs/Best_Practices/Registering_Your_Token), since there is not much activity yet. Let me know if you have doubts.

**Comment by lrgeoemtry** [comment]
we are watching asset here : add.herc.one 
we've met all of your requirements. 
please merge this so any user can get our logo wether they use our thing or not...

**Pull request merged**
