### PR TITLE
add BMX token

### PR DESCRIPTION
**Pull request by ho000easy**

### CODE REVIEW

**Comment by frankiebee** [comment]
This Criteria has not been met for this to be merged:

- [ ] PR should include link to official project website referencing the suggested address.
- [ ] Project website should include explanation of project.
  has not been provided
- [ ] Project should have clear signs of activity, either traffic on the network, activity on GitHub, or community buzz.
- [ ] Must have a ['NEUTRAL' reputation or 'OK' reputation on Etherscan](https://etherscancom.freshdesk.com/support/solutions/articles/35000022146-etherscan-token-reputation-system).

**Comment by ho000easy** [comment]
official web site  referencing the suggested address [contract address](https://support.bitmart.com/hc/en-us/articles/360003255213-Contract-Address)
explanation of BMX [white paper](https://api.bitmart.com/resources/white-paper/bitmart_whitepaper_en_US.pdf)

**Comment by YonnieSun** [comment]
https://support.bitmart.com/hc/en-us/articles/360004830473-BMX

**Comment by YonnieSun** [comment]
https://support.bitmart.com/hc/zh-cn/articles/360004830473-BMX

**Comment by YonnieSun** [comment]
We have completed the missing data, Please check it again.Thank you！

**Comment by YonnieSun** [comment]
We have completed the missing data, Please check it again.Thank you！

**Comment by YonnieSun** [comment]
We have completed the missing data, Please check it again.Thank you！

**Comment by YonnieSun** [comment]
We have completed the missing data, Please check it again.Thank you

**Pull request merged**
