### PR TITLE
Adding KnownOrigin.io

### PR DESCRIPTION
**Pull request by jamesmorgan**
* Website: http://knownorigin.io
* Mainnet smart contract address: https://etherscan.io/address/0xfbeef911dc5821886e1dda71586d90ed28174b7d
* Source code verified

### CODE REVIEW

**Comment by jamesmorgan** [comment]
Morning @estebanmino - it got updated last night - contract is now `NEUTRAL` - thanks

**Comment by estebanmino** [comment]
Hi @jamesmorgan, saw the update it's fine. Also, I saw that there are only 87 holders, for these cases we implemented a new feature called [watchAsset](https://medium.com/metamask/metamask-monthly-september-a2993bc2fa0f). I recommend you to give it a try and let me know what you thoughts, thanks!

**Comment by andygray** [comment]
@estebanmino can you remove the `pending reputation` label. We are still super keen to get onboard with this. We are growing and want to be a thought leader and great example of how to do dApp development.

**Comment by estebanmino** [comment]
@jamesmorgan @andygray merging this

**Comment by jamesmorgan** [comment]
@estebanmino its ERC721 correct? Is this a problem?

**Comment by estebanmino** [comment]
@jamesmorgan sorry for the delay. We don't support collectibles yet but users would be able to see their amount of collectibles as balance. If you change it for ERC20 for the moment, that's the way it's going to work, as Cryptokitties metadata. Let me know any doubt.

**Comment by jamesmorgan** [comment]
@estebanmino switched to erc20 as advised 👍

**Pull request merged**
