### PR TITLE
Add rSAI

### PR DESCRIPTION
**Pull request by pi0neerpat**
Intro to rDAI: https://rdai.money/howitworks.html

Token address can be found on main page, under "Easy to Buidl with!"
https://rdai.money/index.html

Proxy contract (address everyone uses):
https://etherscan.io/token/0xea8b224edd3e342deb514c4176c2e72bcce6fff9

Logic contract (for source code and ABI):
https://etherscan.io/address/0x293908e6352b11a91bc08eeb335644c485d21170

Audit report
https://certificate.quantstamp.com/view/rtoken-ethereum-contracts

Thanks yall!

### CODE REVIEW

**Comment by dpazdan** [comment]
@pi0neerpat do you have an rDAI contract, for the new mcd dai?  If so please submit a new pull request for it.  

Also, do you want to continue to release this one, as rSAI?

**Comment by pi0neerpat** [comment]
@dpazdan thanks for catching this. I'll take the appropriate actions and make a new PR for the new mcd rDAI. It will be announced publicly soon, so having it in MM on day 1 would be the bees knees :bee: 

In the meantime, yes we'd like to go ahead and release this as "rSAI".

**Comment by pi0neerpat** [comment]
Is there a regular release schedule. I'm trying to estimate how long it might take for the new rDAI PR.

from readme:
> We are actively looking for fair and safe ways to maintain a list like this in a decentralized way, because maintaining it is a large and security-delicate task.

Understandable. Maybe you might want to use a bot and delegate this to trusted members of the community? I worked on a hackathon project for this at ETH Denver last year. Might be worth having a conversation to find out what your requirements would be.

https://github.com/dao-git/dao-git-probot

**Comment by dpazdan** [comment]
Can you rename the svg from rdai to rsai? To prevent conflicts with your next PR. 

And regarding the timeframe, there isn't a specific one, though we are trying to improve the process and turnaround time.

**Comment by pi0neerpat** [comment]
done

**Comment by pi0neerpat** [comment]
A new PR for rDAI (#432) has been made. We still wish to continue with this one as well.

Note: the rSAI address has been removed on the website, and is now replaced by the rDAI one.
In case address verification is still needed, you can find it listed on the official rDAI repo https://github.com/rtoken-project/rtoken-contracts#warning-rsai-warning

**Comment by pi0neerpat** [comment]
Hey there @dpazdan  if you are free could you please merge this one and  #432 
Thank you!

**Pull request merged**
