### PR TITLE
add Gram gold coin metadata

### PR DESCRIPTION
**Pull request by ryan-gramgoldcoin**
Website: https://gramgold.co/
Etherscan: https://etherscan.io/token/0x1be7cfd61aa8daaa9ff2f3b8820888f09462d037
GitLab: https://gitlab.com/GramGoldCoin

### CODE REVIEW

**Comment by ryan-gramgoldcoin** [comment]
hi @estebanmino 

the reputation is NEUTRAL right now
please take a look ：）

thank you

**Comment by ryan-gramgoldcoin** [comment]
hi @estebanmino 
and transaction activities 
thank you

**Comment by ryan-gramgoldcoin** [comment]
hi @estebanmino 

thank you for the recommendation  :)

in the mean time, we're trying to list on exchange, decentralized exchanges as well,
once we're approaching dApp for investment through our own website, 
we will use the great feature indeed

get back in line, we will list on exchange at next week, 
may you help to approve this metadata before ?

thank you

**Comment by ryan-gramgoldcoin** [comment]
hi @estebanmino 

anything I can do for this approval ?

thank you :)

**Comment by ryan-gramgoldcoin** [comment]
hi @estebanmino 

the holders and transfers are growing, please take a look

https://etherscan.io/token/0x1be7cfd61aa8daaa9ff2f3b8820888f09462d037

thank you
Ryan

**Comment by estebanmino** [comment]
@ryan-gramgoldcoin closing this for now. I recommend you to check `watchAsset` https://metamask.github.io/metamask-docs/Best_Practices/Registering_Your_Token

**Pull request closed without merging**
