### PR TITLE
SNTVT_Submission

### PR DESCRIPTION
**Pull request by jmanyoma**

### CODE REVIEW

**Comment by jmanyoma** [comment]
Following up on this request

**Comment by xrn** [comment]
Hi @jmanyoma  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

Also can you use EIP 55 version of the address - it should fix tests results

**Comment by jmanyoma** [comment]
> Hi @jmanyoma - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks
> 
> Also can you use EIP 55 version of the address - it should fix tests results



> Hi @jmanyoma - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks
> 
> Also can you use EIP 55 version of the address - it should fix tests results

Thank for for following up, I have made changes to follow EIP55 formating and changed the icon to a SVG icon.

**Comment by xrn** [comment]
@jmanyoma looks like the image name in Json is incorrect after changes

**Comment by jmanyoma** [comment]
> @jmanyoma looks like the image name in Json is incorrect after changes

Sorry about that, changes have been made an committed with updated image name.

**Comment by xrn** [comment]
Thanks @jmanyoma. Looks like the SVG image is incorrect - https://github.com/MetaMask/eth-contract-metadata/blob/b86bcc457b8c035129d45004e0cace7789954177/images/sentivate28.svg I can not display it and we have conflicts between our master and this PR

**Comment by jmanyoma** [comment]
> Thanks @jmanyoma. Looks like the SVG image is incorrect - https://github.com/MetaMask/eth-contract-metadata/blob/b86bcc457b8c035129d45004e0cace7789954177/images/sentivate28.svg I can not display it and we have conflicts between our master and this PR

Sorry for the issues, let me fetch the latest master and create the pull request.

**Comment by xrn** [comment]
@jmanyoma thanks for the changes - but still something is incorrect we should see in diff only new token with image

**Comment by jmanyoma** [comment]
> @jmanyoma thanks for the changes - but still something is incorrect we should see in diff only new token with image

Not sure why, I will be closing this pull request and start a new one. Thank so much for your communication.

**Comment by jmanyoma** [comment]
https://github.com/MetaMask/eth-contract-metadata/pull/586

**Pull request closed without merging**
