### PR TITLE
Add PowerPool

### PR DESCRIPTION
**Pull request by vanphandinh**
**Add PowerPool Concentrated Voting Power token**

- CMC: https://coinmarketcap.com/currencies/powerpool/
- Coingecko: https://www.coingecko.com/en/coins/powerpool-concentrated-voting-power

### CODE REVIEW

**Comment by xrn** [comment]
Hi @vanphandinh - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thank

**Comment by vanphandinh** [comment]
> Hi @vanphandinh - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thank

Thanks for your comment, I have changed the png image to an SVG one. Let review it again. Thank you :)

**Comment by xrn** [comment]
@vanphandinh thanks. I would like to ask - following your etherscan details and symbol can you change the name to "Concentrated Voting Power" without Power Pool - we can have a problem displaying such a long name on all devices at this stage. Please let me know what do you think

**Comment by vanphandinh** [comment]
> @vanphandinh thanks. I would like to ask - following your etherscan details and symbol can you change the name to "Concentrated Voting Power" without Power Pool - we can have a problem displaying such a long name on all devices at this stage. Please let me know what do you think

Thanks for your comment, I've changed as your requirement. Let me know if it has any other problems.

**Review by xrn — APPROVED** [review]

**Pull request merged**
