### PR TITLE
Upload logo of ZEON Network

### PR DESCRIPTION
**Pull request by ZeonNetwork**
Upload logo of ZEON Network

### CODE REVIEW

**Comment by ZeonNetwork** [comment]
Zeon is listed on top exchanges.
www.zeon.network - you can see more info.
Can you please add token in the metamask’s list and upload our logo (Commit
#266)?


пт, 22 марта 2019 г. в 20:21, Esteban Miño <notifications@github.com>:

**Comment by ZeonNetwork** [comment]
> Hi @ZeonNetwork, we need at least NEUTRAL reputation on etherscan in order to merge, this token has UNKNOWN reputation. Could you also provide additional required information please? Thanks.

More than 20K transfers of tokens. Did you make a review?

**Comment by estebanmino** [comment]
Hi @ZeonNetwork I'm talking about [this](https://etherscancom.freshdesk.com/support/solutions/articles/35000022146-etherscan-token-reputation-system). Is in the criteria to be able to add new tokens. Let me know if you have any doubt. Thanks.

**Comment by ZeonNetwork** [comment]
*@estebanmino* reputation is updated on Etherscan. Check please

>

**Comment by ZeonNetwork** [comment]
*@estebanmino reputation is updated on Etherscan. Check please*

**Comment by ZeonNetwork** [comment]
@estebanmino reputation is updated on Etherscan. Check please

**Pull request merged**
