### PR TITLE
Added REDC

### PR DESCRIPTION
**Pull request by Redcabllc**

### CODE REVIEW

**Comment by Redcabllc** [comment]
*    Add the icon mentioned in the data added.

Done https://github.com/Redcabllc/eth-contract-metadata/blob/master/images/redcab.png

  *    Include link to official project website referencing the suggested address.

https://redcab.io

  *    Project should have clear signs of activity.

Telegram community 20K, Twitter 15K, FB 4K


On Aug 13, 2018, at 9:31 PM, Esteban Miño <notifications@github.com<mailto:notifications@github.com>> wrote:


@estebanmino requested changes on this pull request.

Hi @Redcabllc<https://github.com/Redcabllc> please add additional information in order to add this token. Thanks.

  *    Add the icon mentioned in the data added.
  *    Include link to official project website referencing the suggested address.
  *    Project should have clear signs of activity.

**Comment by estebanmino** [comment]
@Redcabllc all criteria fulfilled but the icon is not in this PR, is on your fork but the last commit is not pushed here.

**Comment by Redcabllc** [comment]
What do you suggest?
I added the icon to this mail, and this is the link to it on impure as well. https://i.imgur.com/fSyzYai.png



[cid:11AED20F-6D24-4940-855A-D0F2C929F5A0]



On Aug 13, 2018, at 9:48 PM, Esteban Miño <notifications@github.com<mailto:notifications@github.com>> wrote:


@Redcabllc<https://github.com/Redcabllc> all criteria fulfilled but the icon is not in this PR, is on your fork but the last commit is not pushed here.

**Comment by estebanmino** [comment]
Just push it into this PR and ping me, I'll merge it then.

**Comment by Redcabllc** [comment]
redcab

**Comment by Redcabllc** [comment]
done

On Aug 13, 2018, at 10:00 PM, Esteban Miño <notifications@github.com<mailto:notifications@github.com>> wrote:


Just push it into this PR and ping me, I'll merge it then.

**Pull request merged**
