### PR TITLE
Add HUSD Info

### PR DESCRIPTION
**Pull request by ycclaude**
Contract Address: 0xdf574c24545e5ffecb9a659c229253d4111d87e1
Website: https://www.stcoins.com/
Etherscan: https://etherscan.io/token/0xdf574c24545e5ffecb9a659c229253d4111d87e1
Twitter: https://twitter.com/Stablecoin_HUSD
Contact: support@stcoins.com

### CODE REVIEW

**Comment by xrn** [comment]
Hi @ycclaude - tests are failing because of invalid Json (double "}") can you fix it, please? Will be awesome also if you can add SVG logo in this PR

**Comment by ycclaude** [comment]
> Hi @ycclaude - tests are failing because of invalid Json (double "}") can you fix it, please? Will be awesome also if you can add SVG logo in this PR

Thank you xrn, I have fixed. But to be honest, I am not a programmer, so I don't know how to add logo in this PR. I just submitted a new PR here : https://github.com/MetaMask/eth-contract-metadata/pull/590

If this works?

Thank you.

**Comment by xrn** [comment]
Thanks, @ycclaude will be great if you can try to add a logo to this pull request as well, but most important is that you have to fix the address. There is a requirement that the address has to be in EIP-55 format - without that, I can not review that PR - thanks.

**Review by xrn — APPROVED** [review]

**Comment by ycclaude** [comment]
Thank you @xrn , I saw the PR is merged , but the HUSD icon hasn't show on meta mask yet. So we should wait for the deployment right? Thanks.

**Comment by xrn** [comment]
@ycclaude correct

**Pull request merged**
