### PR TITLE
Add BorisCoin Image

### PR DESCRIPTION
**Pull request by bmann**
Hello! I would like to have my BorisCoin image show up in MetaMask.

I am closing in on 100 unique address holders.

My reputation on EtherScan is UNKNOWN https://etherscan.io/token/0x919d0131fa5f77d99fbbbbace50bcb6e62332bf2

I applied three months ago to EtherScan, but since this is a personal token, they never got back to me.

Please let me know what the next steps are in getting my image added to MetaMask.

### CODE REVIEW

**Comment by bmann** [comment]
@estebanmino I find it awkward that you're outsourcing reputation to a third party. EtherScan won't approve me as far as I can tell because I'm not an ICO.

Do you have any suggestions on what I can do?

**Comment by estebanmino** [comment]
@bmann I would recommend you to add the token by yourself manually on MetaMask, there is a section in `Add Tokens` to do so.

image

**Comment by bmann** [comment]
I understand that is how it works. I need to message a 100 of my friends and acquaintances to do the same. Same goes if I run a small token in my hometown or numerous other community use cases. 

Are there any plans to decouple from Etherscan? Should I open a separate issue for that discussion?

**Comment by estebanmino** [comment]
In fact we are working on one specification to address this, https://ethereum-magicians.org/t/eip-747-wallet-watchasset/1048/7.
There you can see the proposal, docs and the first implementation of this on MetaMask, waiting for community debate.

**Comment by estebanmino** [comment]
Closing this due to inactivity, feel free to reopen. In addition we implemented [watchAsset](https://medium.com/metamask/metamask-monthly-september-a2993bc2fa0f) the feature mentioned before I recommend you to use it, with this you could suggest your users to track your token.

**Pull request closed without merging**
