### PR TITLE
Adding Cpollo ERC20 Token and Cpollo.svg

### PR DESCRIPTION
**Pull request by JoaoCampos89**
Cpollo Project, you can check our project here: 

[Cpollo Site](https://cpollo.info/)
[Telegram](https://t.me/cpollo2)
[Twitter](https://twitter.com/cpollo_)

### CODE REVIEW

**Comment by JoaoCampos89** [comment]
[Etherscan verified source code](https://etherscan.io/address/0x7064aab39a0fcf7221c3396719d0917a65e35515#code)

**Comment by JoaoCampos89** [comment]
Hi Esteban, 

Cpollo is now neutral at Etherscan, can you please merge this.

Best Regards,
João Campos
Lead Blockchain Developer at Cpollo

**Comment by estebanmino** [comment]
@JoaoCampos89 just noticed that the logo is more than 0.5 MB, could you please change it for a smaller one? Less than 50 KB would be ideal. Thanks.

**Comment by JoaoCampos89** [comment]
@estebanmino I changed the logo size as requested. Now the size is 6 kB, thanks for pointing that!

**Pull request merged**
