### PR TITLE
Brickblock (BBK)

### PR DESCRIPTION
**Pull request by mattgstevens**
### Project website
https://www.brickblock.io

### Project whitepaper
https://www.brickblock.io/Brickblock_General_Whitepaper.pdf

## Verified source on etherscan
https://etherscan.io/address/0x4a6058666cf1057eac3cd3a5a614620547559fc9#readContract

### CODE REVIEW

**Comment by mattgstevens** [comment]
will follow up on why the reputation on etherscan.io is "Unknown"

**Comment by estebanmino** [comment]
Hi @mattgstevens perfect, ping me when is done.

**Comment by mattgstevens** [comment]
@estebanmino so far its not clear when the etherscan reputation will be changed / if they will notify when they have reviewed.

posting the ticket out here for visibility to others wondering about the status of this.
https://etherscancom.freshdesk.com/public/tickets/0365672b183cc5376d8df1d33d8a57f77dc93fc75779b9c046881ed6294cd538

**Comment by mattgstevens** [comment]
@estebanmino update is in on etherscan; "Neutral" reputation achieved!
https://etherscan.io/token/0x4a6058666cf1057eac3cd3a5a614620547559fc9

Think this is ready to merge.

**Comment by estebanmino** [comment]
Hi @claudiobarillas we are releasing a new version of MetaMask, if you have the version 4.10 it should appear.

**Pull request merged**
