### PR TITLE
Add TOP to list

### PR DESCRIPTION
**Pull request by masteraiyuan**
Add support for the TOP ERC-20 token.

- Website: http://www.topnetwork.org
- Twitter: @topnetwork_top
- Telegram: https://t.me/topnetwork_top
- News Channel: https://t.me/top_network
- Medium: https://medium.com/@topnetwork

TOP Network is a decentralized blockchain ecosystem composed of public blockchain, DApps & decentralized communication.

### CODE REVIEW

**Comment by xrn** [comment]
Hi @masteraiyuan  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by masteraiyuan** [comment]
> Hi @masteraiyuan - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

Thank you for your reply.  I have upload the SVG file , and update the json , please review again. Thanks

**Comment by xrn** [comment]
@masteraiyuan can you also resolve conflicts, please?

**Comment by masteraiyuan** [comment]
@xrn sorry I miss it last time, It's ok now!

**Review by xrn — APPROVED** [review]

**Pull request merged**
