### PR TITLE
Add GET asset

### PR DESCRIPTION
**Pull request by kasper-keunen**
Token Contract Address(ERC20): 0x8a854288a5976036a725879164ca3e91d30c6a1b
Etherscan: https://etherscan.io/address/0x8a854288a5976036a725879164ca3e91d30c6a1b#code
Full name: Guaranteed Entrance Token
Token Name (from contract): GET
Token Decimals (from contract): 18
Token Symbol (from contract): GET
Uniswap V2 Pair Address of Token: https://uniswap.info/token/0x8a854288a5976036a725879164ca3e91d30c6a1b or
Github: https://github.com/GETProtocol/GET-Protocol-statechange-counter 

Link to the official homepage of token: https://get-protocol.io/ (reference to address: https://get-protocol.io/token#details) 
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/get-protocol/ & https://www.coingecko.com/en/coins/get-protocol

### CODE REVIEW

**Comment by OlivierBiggs** [comment]
Would be great to have this done - the GET community has been waiting for some time now.

**Comment by Cryptocosy** [comment]
A project as legit as it can get. 
Can't go wrong there

**Review by RobStof — APPROVED** [review]
Please add GET Protocol support.

**Review by S01E01 — APPROVED** [review]
This would be a great addition

**Review by kasper-keunen — COMMENTED** [review]
Nothing changed to the request. Just processed the recently added PLR token.

**Comment by kasper-keunen** [comment]
Hi @xrn, noticed you where managing these repos. Would be highly appreciated if we could have this request merged.  There are 2 other tokens that with the same ticket GET. Both are confirmed scams (https://etherscan.io/token/0x60c68a87be1e8a84144b543aacfa77199cd3d024 & https://etherscan.io/token/0x3364fb62274ad4659bc5162a9ba4b84c73784f58). Every week I am getting emails of people that have been duped. Etherscan has helped us by putting the other 'fake GETs' below us in the etherscan search bar - only big culprit for confusion is still Metamask.. If you need anything from us do let me know!

**Review by xrn — APPROVED** [review]

**Comment by kasper-keunen** [comment]
Thanks!

**Pull request merged**
