### PR TITLE
Added metadata for CrowdstartCoin / XSC

### PR DESCRIPTION
**Pull request by crowdstartcapital**
Added metadata for CrowdstartCoin / XSC including an update to the json file and the image file as specified.

### CODE REVIEW

**Comment by crowdstartcapital** [comment]
Hi Blaine, 

Yes we do have a SVG version of the image file.  I've attached it as a zip archive. 

Please let me know if this is an acceptable input. 

Rebecca

[XSC Logo.svg.zip](https://github.com/MetaMask/eth-contract-metadata/files/1618500/XSC.Logo.svg.zip)

**Comment by blmalone** [comment]
@crowdstartcapital Thanks, the image looks good. 

We also need to see the contract address `0x0F513fFb4926ff82D7F60A05069047AcA295C413` that you included linked on some public official documents. For example, if it's displayed on your website. Please post a link. 

Thanks.

**Comment by crowdstartcapital** [comment]
Hi Blaine,

The contract address is posted on our website and the website is also listed on etherscan. The contract code has been verified there.

http://crowdstart.capital/xsc-overview/

Thanks & best regards,
Rebecca

**Comment by blmalone** [comment]
Thanks Rebecca @crowdstartcapital 

FYI: @danfinlay

**Comment by danfinlay** [comment]
Hi @crowdstartcapital, could you please include the svg as the file included by the PR, not just attached to the discussion?

**Comment by crowdstartcapital** [comment]
@danfinlay I've updated the .json but the binary file (.jpg) doesn't seem to allow me to make modifications.  Is there another way?

**Comment by danfinlay** [comment]
Yes, remove the .jpg and upload the .svg.

**Comment by crowdstartcapital** [comment]
@danfinlay Done. Removed the .jpg and uploaded the .svg. Thanks for the help.

**Pull request merged**
