### PR TITLE
feat(add-token): MM-000 add STORM ERC-20 token + linting

### PR DESCRIPTION
**Pull request by tkostantinov-digihey**
- add storm token logo
    - add address and description
    - remove trailing spaces
    
https://www.stormx.io/

https://etherscan.io/token/0xd0a4b8946cb52f0661273bfbc6fd0e0c75fc6433

### CODE REVIEW

**Comment by estebanmino** [comment]
@tkostantinov-digihey could you fix conflicts please? Thanks

**Comment by tkostantinov-digihey** [comment]
@estebanmino conflict resolved.

**Comment by calvinh8** [comment]
Hi @estebanmino, I wonder if we can get this merged in so we can have STORM showing in MetaMask? Thanks!

**Comment by alexhidalgo** [comment]
Hi @estebanmino @pi0neerpat @ososco  could we please have you review this PR? We are about to launch our Rewards Program which has MetaMask as our preferred method for users to connect to our app.

**Comment by alexhidalgo** [comment]
> Checks out.

@rekmarks thanks for the quick response. This will really help us with our Rewards Program launch this week.

**Comment by rekmarks** [comment]
You got it! This should be in production by early next week at the latest.

**Pull request merged**
