### PR TITLE
Add AEUR token

### PR DESCRIPTION
**Pull request by phraktle**
Adding the Augmint Euro decentralized stablecoin.

For reference, see:
 * https://www.augmint.org/
 * Token: https://etherscan.io/token/0xc994a2deb02543db1f48688438b9903c4b305ce3

### CODE REVIEW

**Comment by phraktle** [comment]
Hi @estebanmino,

Thanks for the feedback. While the `watchAsset` feature is helpful, it's not actually a solution to the problem that prompted this PR, namely that when people with MetaMask wallets receive our tokens they do not see them listed properly.

You do have my full support on getting rid of centralized registries such as this. However, refusing a proper PR is actually putting projects at a UX disadvantage compared to others that came before (popular or not), so I would like to request that you reconsider your policies based on fairness and include new submissions that fulfill the requirements or remove all tokens listed in this registry.

**Comment by keo** [comment]
Please add this. Thank you.

**Comment by phraktle** [comment]
@estebanmino the `watchAsset` API is inadequate even for the purpose it was meant to address. See https://github.com/ethereum/EIPs/pull/1426#issuecomment-472350298

Until Ethereum and Metamask can properly address the problem of detecting tokens in wallets, I urge Metamask maintainers to merge requests to add tokens that fulfill the listed criteria (such as AEUR), instead of further politicizing the process and making it a popularity contest.

**Comment by debreczeni** [comment]
👍 Would love to see this! <3

**Comment by oyunrdn** [comment]
It would be great if you add Augmint Euro.

**Comment by godavid** [comment]
Augmint EUR would be nice

**Comment by szerintedmi** [comment]
+1 one for adding Augmint AEUR

**Comment by hubudibu** [comment]
+1 please add,  💖  Augmint

**Comment by reyrodrigez** [comment]
+1 AugmintEUR, would be great

**Comment by estebanmino** [comment]
Hi @phraktle, due to the community activity I'll close this PR, 73 holders is not enough to add it to MetaMask. I encourage you to give `watch asset` feature a try. Thanks.

**Comment by phraktle** [comment]
@estebanmino how many holders are enough?

**Pull request closed without merging**
