### PR TITLE
Add HEX token

### PR DESCRIPTION
**Pull request by togoshige**
HEX is an ERC20 token, it is the First Blockchain Certificate of Deposit

Website:  https://hex.win/
Contract:  https://etherscan.io/token/0x2b591e99afe9f32eaa6214f7b7629768c40eeb39

Top 10 Dapp on DappsRadar:  https://dappradar.com/
Top 20 Dapp on StateOfTheDapps:  https://www.stateofthedapps.com/rankings

### CODE REVIEW

**Comment by kbahr** [comment]
This has languished for a few months. HEX is top 40 market cap now: https://coinpaprika.com/coin/hex-hex/

Also #1 liquidity in Uniswap: https://uniswap.info/

**Comment by danfinlay** [comment]
We encourage projects to use EIP-747 to register their tokens in users' wallets, and this case is no exception to that recommendation.
https://docs.metamask.io/guide/registering-your-token.html

Especially in light of the amount of controversy around this token, and amount of support for outright blocking it, I do not anticipate us recommending it to users by default.

**Comment by campassi** [comment]
Bitcoin was controversial too in the early days.

**Comment by firebun1337** [comment]
> We encourage projects to use EIP-747 to register their tokens in users' wallets, and this case is no exception to that recommendation.
> https://docs.metamask.io/guide/registering-your-token.html
> 
> Especially in light of the amount of controversy around this token, and amount of support for outright blocking it, I do not anticipate us recommending it to users by default.

Any new thoughts in the last 6 months?

**Comment by xrn** [comment]
Hi @togoshige  - I would like to merge this request but there is a new requirement that the logo has to be in SVG format. Can I ask you to add it as a replacement for the PNG one? Thanks

**Comment by firebun1337** [comment]
@xrn thanks for the response on this -- i made a separate pull request to address the svg requirement here: https://github.com/MetaMask/eth-contract-metadata/pull/594

**Pull request closed without merging**
